### ISSUE TITLE
Allow to specify a seed to get allways the same data.

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#119]
When using objectfiller with tests, it might be necessary to use allways the same data. A full fledged filler setup is to much in this case, because we would like to generate data to keep the amount of code low, but this data should be generated allways the same way to make sure that the tests run the same ways each and every time.

**Comment by Tynamix** [comment]
Hey Hendrik :).
Its already implemented in ObjectFiller 1.5.5.

https://objectfillernet.readme.io/reference#set-random-seed

**Comment by HerrLoesch** [comment]
Shame on me...
