### ISSUE TITLE
Give us control over Collection counts

### ISSUE THREAD

**Issue by MikeGriffinReborn** [Tynamix/ObjectFiller.NET#121]
The Collectionizer doesn't work for classes that we create, for instance:

        public class MetaData
        {
            public IEnumerable<BaseRecipe> BaseRecipes { get; set; }
        }

I want say between 1 and 5 BaseRecipes, not 23 ...  I cannot seem to control this so I have to go in and manually remove so many after the filler.Create() calls ...

**Comment by Tynamix** [comment]
Hey!
You have control over list count. Its just a little bit hidden:

```
namespace ConsoleApp3
{
    public class MetaData
    {
        public IEnumerable<BaseRecipe> BaseRecipes { get; set; }
    }

    public class BaseRecipe
    {
        public string Name { get; set; }
        public List<BaseRecipe> SubRecipe { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            Filler<MetaData> filler = new Filler<MetaData>();

            filler.Setup()
                .ListItemCount(1, 5);

            var result = filler.Create();
        }
    }
}
```
