### ISSUE TITLE
.Net 5.0?

### ISSUE THREAD

**Issue by OpResCodes** [Tynamix/ObjectFiller.NET#127]
Could you migrate it to the latest .net version? :)

**Comment by HerrLoesch** [comment]
I guess the easiest way would be to migrate it completely to .NET 5.0 call it version 2 and cut all dependencies to earlier .NET versions. This would mean, that we are not backwards compatible but it would be far easier to handle in the future.

**Comment by Tynamix** [comment]
Oops? Im little out of .NET development because i switched to Java in my job but was there a breaking change to the NETStandard? ObjectFiller uses .NET Standard 1.0 which is also implemented by .NET 5. So why should it be necessary to upgrade?

**Comment by Tynamix** [comment]
I added target framework moniker for NETStandard1.3 and NETStandard2.0. If you now reference ObjectFiller.NET it does not ask for one million dependencies anymore :)
