### ISSUE TITLE
Support for IDictionary

### ISSUE THREAD

**Issue by wztech0192** [Tynamix/ObjectFiller.NET#130]
The filler will throw off a `System.ArgumentException` when create a object that contains property of IDictionary type. This is because it misrecognize the IDictionary type as IEnumerable type.

**Comment by Tynamix** [comment]
Hey! Thanks for contribution. Will have a look at it.

**Comment by wztech0192** [comment]
Any updates on this issue?

**Comment by Tynamix** [comment]
Will be released in next release. Thanks for contribution and sorry for the loooong delay. Switched my employer and now im Java Developer and not .NET anymore.
