### ISSUE TITLE
BUG:  Creating Multiple Objects

### ISSUE THREAD

**Issue by cjdutoit** [Tynamix/ObjectFiller.NET#140]
The behaviour of creating multiple random objects is not behaving as expected when providing custom values.

EXPECTED BEHAVIOUR:  `CreateRandomTestFiller().Create(count: 3).ToList();` should always create an object with different values unless a static value is assigned.

To reproduce you can use the following class:
```
    internal class Test
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime TimeStamp { get; set; }
    }
```
with this test:
```
    public class FillerTests
    {
        [Fact]
        public void ShouldCreateMultipleObjects()
        {
            // given
            List<Test> tests = CreateRandomTests();

            // then
            tests.Select(test => test.Id).Distinct().Count().Should().Be(tests.Count);
            tests.Select(test => test.Name).Distinct().Count().Should().Be(tests.Count);
            tests.Select(test => test.TimeStamp).Distinct().Count().Should().Be(tests.Count);
        }


        private static int GetRandomNumber() =>
            new IntRange(min: 2, max: 10).GetValue();

        private static DateTime GetRandomDateTime() =>
            new DateTimeRange().GetValue();

        private static string GetRandomString() =>
            new MnemonicString(wordCount: 1, wordMinLength: 3, wordMaxLength: 10).GetValue();

        private static List<Test> CreateRandomTests()
        {
            return CreateRandomTestFiller()
                .Create(count: 3)
                    .ToList();
        }

        private static Filler<Test> CreateRandomTestFiller()
        {
            var filler = new Filler<Test>();
            filler.Setup();

            return filler;
        }
    }
```
**EXPECTED**:  The above pass the test with unique values:
![image](https://github.com/Tynamix/ObjectFiller.NET/assets/797750/673617f4-67e6-40c1-834b-3e3c01b00ceb)

Now lets alter the filler slightly to cater for expected values within a certain range or length requirement.
```
        private static Filler<Test> CreateRandomTestFillerWithSpecialValues()
        {
            var filler = new Filler<Test>();

            filler.Setup()
                .OnProperty(test => test.Id).Use(GetRandomNumber())
                .OnProperty(test => test.Name).Use(GetRandomString())
                .OnProperty(test => test.TimeStamp).Use(GetRandomDateTime());

            return filler;
        }
```
So with this change I am still expecting 3 different object with different values for the properties.  I have just specify a `Use()` to use a random value from those methods that would comply with either the range of the int/datetime or length requirement for the string.

**UNEXPECTED OUTCOME:** Test Fails with non unique values for the properties with the `.Use(...)` assignment.
![image](https://github.com/Tynamix/ObjectFiller.NET/assets/797750/8eeda4e4-9efb-4b3a-b282-f5eff72b7b94)

- Description is unique (The only property that did not het the custom `.Use(...)`
- Id is not unique.
- Name is not unique
- TimeStamp is not unique.

Not sure if the results of those methods is cached, but were not expecting that behaviour.

**Comment by Tynamix** [comment]
Thank you for your question and sorry for the late answer. The solution is simple. If you use the Use() function with a value as parameter it will always return the same value. So your GetRandomNumber() gets called exactly once and then never again:
![image](https://github.com/Tynamix/ObjectFiller.NET/assets/7276477/56171fca-2a47-451c-8746-cb739086e938)

But if you use the Use() function with a ```Func<T>``` than it always calls this function when objectfiller will create a new value:
![image](https://github.com/Tynamix/ObjectFiller.NET/assets/7276477/7e5565fd-ffa0-4dd7-ad0d-1e5184f8bf7b)

So just change this code:
```csharp
      private static Filler<Test> CreateRandomTestFillerWithSpecialValues()
      {
          var filler = new Filler<Test>();

          filler.Setup()
              .OnProperty(test => test.Id).Use(GetRandomNumber())
              .OnProperty(test => test.Name).Use(GetRandomString())
              .OnProperty(test => test.TimeStamp).Use(GetRandomDateTime());

          return filler;
      }
```

to this:
```csharp
        private static Filler<Test> CreateRandomTestFillerWithSpecialValues()
        {
            var filler = new Filler<Test>();

            filler.Setup()
                .OnProperty(test => test.Id).Use(() => GetRandomNumber())
                .OnProperty(test => test.Name).Use(() => GetRandomString())
                .OnProperty(test => test.TimeStamp).Use(() => GetRandomDateTime());

            return filler;
        }
```

and everything should work as expected 👍
