### ISSUE TITLE
IEnumerable<T> Create(int count) creates different results when reference is called more than once

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#42]
var filler = new Filler<Office>();
            IEnumerable<Office> offices = filler.Create(1);

            CollectionAssert.AreEquivalent(offices, offices);

Will fail because the compared collection does not contain the same instances. I guess the reason is, that Create uses yield which creates new instances when ever the enumerator if IEnumerable is used. E.g. in case of foreach.

**Comment by Tynamix** [comment]
fixed...will be shipped with the next version
