### ISSUE TITLE
Lipsum Randomizer is not random enough

### ISSUE THREAD

**Issue by bitbonk** [Tynamix/ObjectFiller.NET#47]
Using the following code, allmost all instances of Foo have the same description text (sometime there are two versions of text in those 1000 instances):

    var foos = new Filler<Foo>();
    filler.Setup()
        .OnProperty(foo => foo.Description)
        .Use(new Lipsum(LipsumFlavor.LoremIpsum))
        .Create(1000);

Be default I would have expected that they all have a different text.

The reason why this happens is probably because the `Lipsum` randomizer creates a new `Random` instance at the beginning of each `GetValue()` call (with the same seed, because in most cases `Environment.TickCount` has the same value for all 1000 calls).

Instead it should create the `Random` instance in the `Lipsum` constructor store it in a field and use that same istance for each `random.Next()` call inside `GetValue()`

I can work around this issue by doing:

    var seed = 0;
    var filler = new Filler<Todo>();
    filler.Setup()
        .OnProperty(t => t.Description)
        .Use(() =>new Lipsum(LipsumFlavor.ChildHarold, seed++).GetValue()))
        .Create(1000);

**Comment by HerrLoesch** [comment]
Should be fixed with my last checkin. Thank you for providing such detailed description.
