### ISSUE TITLE
Nullable Enumerations can't be generated

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#48]
An InvalidOperationException is thrown if a class has a nullable enumeration:

public class MyClass { public MyEnum? TheEnum {get; set; } } 

public enum MyEnum { A, B, C }

Randomizer<MyClass>.Create(); <-- Exception

Same happens with the filler class.

**Comment by Tynamix** [comment]
Fixed! Thanks for reporting this issue...
