### ISSUE TITLE
Error when setting up strings with numerals

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#57]
I have following code which will fail on Create:

            var filler = new Filler<Address>();
            filler.Setup().OnProperty(x => x.Id).Use("1");

            this.address = filler.Create();

Id is a string in which numerals are stored like 1, 2 or 3. It seems that the filler tries to convert the number into an integer and is then unable to assign this number to the actual string.

**Comment by Tynamix** [comment]
I've wrote the following unit test
```csharp
    
        public class Bug57
        {
              public string Id { get; set; } 
        }

        [Fact]
        public void CheckIfBug57IsFixed()
        {
            var filler = new Filler<Bug57>();
            filler.Setup().OnProperty(x => x.Id).Use("1");

            var bug57 = filler.Create();

            Assert.Equal("1", bug57.Id);
        }
```
it runs without error. Which error occured on your site?
