### ISSUE TITLE
Provide a way to create Setups without the need of a filler.

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#58]
Current we need to do something like this to create a setup:

            var categoryFiller = new Filler<Category>();
            var categorySetup = categoryFiller.Setup().OnType<int>().Use(new IntRange(1, 100)).Result;

It would be nice to skip the Filler and create a setup like this:

            var categorySetup = Setup<Category>.OnType<int>().Use(new IntRange(1, 100)).Result;

**Comment by Tynamix** [comment]
There is already a solution implemented (by you :smile: )...
Use:
var  var categorySetup = FillerSetup.Create<Category>().OnType<int>().Use(new IntRange(1, 100)).Result;

Its more or less the same :+1:

**Comment by HerrLoesch** [comment]
Oh well, did I? Great I can read my mind...
