### ISSUE TITLE
Shorter strings by default

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#59]
When I generate a string then I get usually something like this by default: "Tabedojimij Vedezosodul magoserotom gowatafumim Dibopaselim sorokesosoj Kirugisebob vorowavucob Jatalefihup gunirapejol Jibucelonez Jabebuwujuw Kajafijacuk wahikokakef Bicakujakiw Lenutekovaf sojabecojas banegikumet ziwagemihuj Vazatotudon"

That's not wrong but I usualy only need a short phrase like "Tabedojimij". I would suggest that we change the default behaviour of the filler so it creates only one word when no setup for strings is given.

**Comment by Tynamix** [comment]
Is here a voting system somewhere :thought_balloon: :question: I will think about it... :smile:

**Comment by HerrLoesch** [comment]
You could use Twitter for voting but I guess we two would be the only two answering...

Here a snippet where the long strings are a realy pain:

  this.addresses = Randomizer<Address>.Create(2).ToList();

I just want a couple of strings for streetname, city name and so on, but I get a whole novel. That's quite a pain while unit testing.

**Comment by anjaHirschmueller** [comment]
+1
