### ISSUE TITLE
Bug with Thread Safe Random Support

### ISSUE THREAD

**Issue by blmeyers** [Tynamix/ObjectFiller.NET#60]
There's currently a bug with the implementation of thread safe random access that was committed.  It uses a static constructor to initialize a ThreadStatic marked field, which will cause subsequent threads to throw a null reference exception.  Initialization at the field level or static constructor level for a ThreadStatic field will only ever run once on the first thread to reach the type, any subsequent threads will access an uninitialized variable.

This is an important feature to my company's usage of the library and we were hoping to avoid maintaining a fork just for this change, so I'm submitting a pull request to add a new unit test and correct the bug.  More details in the PR (#61)

**Comment by Tynamix** [comment]
Hey! Thank you very much for this pull request. I will look at it this evening! I will then merge and release a new version as soon as possible (maybe this weekend).

Cheers!
Roman

**Comment by Tynamix** [comment]
I changed your unit test because is asserts two lists, which are always not equal because they are two different references. Anyway, thank you for the bugfix!
:+1:
