### ISSUE TITLE
Creating new plugin / Getting types registered in the randomizer.

### ISSUE THREAD

**Issue by zo0o0ot** [Tynamix/ObjectFiller.NET#63]
Hello.  I ran into an issue when trying to fill in a System.Drawing.Color value using object filler.
Here's the error message that happens when running the test: 
```
System.Exception : The type [Color] was not registered in the randomizer.
```

Here's the stacktrace:
```
Result StackTrace:	
at Tynamix.ObjectFiller.Filler`1.GetRandomValue(Type propertyType, FillerSetupItem setupItem)
at Tynamix.ObjectFiller.Filler`1.CreateAndFillObject(Type type, FillerSetupItem currentSetupItem, HashStack`1 typeTracker)
at Tynamix.ObjectFiller.Filler`1.FillInternal(Object objectToFill, HashStack`1 typeTracker)
at Tynamix.ObjectFiller.Filler`1.Create()
```

To attempt to solve this issue, I followed the documentation listed [on how to make a plugin](https://objectfillernet.readme.io/docs/how-to-write-a-objectfillernet-plugin), and my code is as follows:
```
        public class argbColorPlugin : IRandomizerPlugin<Color>
        {
            private readonly Random r = new Random();
            private readonly List<Color> allColors =
            new List<Color>()
            {
                System.Drawing.Color.Beige,
                System.Drawing.Color.FromArgb(new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue())
            };

            public Color GetValue()
            {
                return allColors[r.Next(0, allColors.Count)];
            }
        }
```

Even after calling the plugin instead of passing in a Color, it still has the same error. 

Here's how I'm calling it:

```
.OnProperty(x => x.FontColor).Use(new argbColorPlugin().GetValue())
```

It's in the middle of a bunch of other properties, mostly floats, but a couple other object types are present.  All of the rest of them seem to work pretty well.

Is there something that I'm supposed to do in order to register the type in the randomizer?
Thanks!

**Comment by zo0o0ot** [comment]
It looks like these types are registered in `private void SetDefaultRandomizer()` in `FillerSetupItem.cs`.

**Comment by Tynamix** [comment]
Hmm, strange... i just tried it out in a new Console Application:

```csharp
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Tynamix.ObjectFiller;

namespace ConsoleApplication4
{
    class Program
    {
        public class argbColorPlugin : IRandomizerPlugin<Color>
        {
            private readonly System.Random r = new System.Random();
            private readonly List<Color> allColors =
            new List<Color>()
            {
                System.Drawing.Color.Beige,
                System.Drawing.Color.FromArgb(new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue())
            };

            public Color GetValue()
            {
                return allColors[r.Next(0, allColors.Count)];
            }
        }

        public class Bug63Poco
        {
            public double SomeNumber { get; set; }
            public Color SomeColor { get; set; }
        }

        static void Main(string[] args)
        {
            Filler<Bug63Poco> filler = new Filler<Bug63Poco>();

            filler
                .Setup()
                .OnProperty(x => x.SomeNumber).Use(new DoubleRange(10, 1000))
                .OnProperty(x => x.SomeColor).Use(new argbColorPlugin().GetValue());

            Bug63Poco bug63Poco = filler.Create();

            Console.WriteLine(bug63Poco.SomeNumber);
            Console.WriteLine(bug63Poco.SomeColor);
            Console.ReadLine();
        }
    }
}
```

It works for me... I could imagine that you maybe use another Property of type "Color"...? Maybe a property named BackgroundColor or something like that? :smile: If that is the case you have to setup each Property OR you just setup the Type System.Drawing.Color itself instead of setting up each Property. For that you can use `.OnType<Color>`. I modify the example from above (Look where i made the comment!):

```csharp
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Tynamix.ObjectFiller;

namespace ConsoleApplication4
{
    class Program
    {
        public class argbColorPlugin : IRandomizerPlugin<Color>
        {
            private readonly System.Random r = new System.Random();
            private readonly List<Color> allColors =
            new List<Color>()
            {
                System.Drawing.Color.Beige,
                System.Drawing.Color.FromArgb(new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue())
            };

            public Color GetValue()
            {
                return allColors[r.Next(0, allColors.Count)];
            }
        }

        public class Bug63Poco
        {
            public double SomeNumber { get; set; }
            public Color FontColor { get; set; }
            public Color BackgroundColor { get; set; }

        }

        static void Main(string[] args)
        {
            Filler<Bug63Poco> filler = new Filler<Bug63Poco>();

            filler
                .Setup()
                .OnProperty(x => x.SomeNumber).Use(new DoubleRange(10, 1000))
                // !!! SETUP FOR ALL PROPERTIES OF TYPE COLOR! !!!
                .OnType<Color>().Use(new argbColorPlugin()); 

            Bug63Poco bug63Poco = filler.Create();

            Console.WriteLine(bug63Poco.SomeNumber);
            Console.WriteLine(bug63Poco.FontColor);
            Console.WriteLine(bug63Poco.BackgroundColor);
            Console.ReadLine();
        }
    }
}
```

Does this help?

Thanks for using ObjectFiller!

Cheers,
Roman

**Comment by zo0o0ot** [comment]
Thank you for your reply.  It's always nice to get feedback from one of the primary authors.

I did try commenting out the .OnProperty reference and adding the .OnType<Color>() instead, but I still run into the same error.

The weird thing is that I had this exception occur even before creating the new plugin.  I had originally passed in the color manually, by creating an actual System.Drawing.Color object it in the public filler class and just passing in the variable name in `.Use(...)`.  The reason that I wrote the plugin was to see if the plugin would fix the issue with the randomizer registration.

Does it matter that I'm creating a _fillerSetup object and calling the setup afterwards?  I'm just trying to figure out why my code would end up calling `SetDefaultRandomizer()` and end up with the error message that you have there.

I'm not sure if the version info is relevant, but I'm running version 1.4.1.0 of ObjectFiller.

**Comment by zo0o0ot** [comment]
I created a new method that takes out the abstraction of creating the `_fillerSetup` object and tries to do the entire setup within the test object itself.  I still have the same error, with either the `.OnProperty` or  `.OnType` referring to the color.

Here's something that may help with troubleshooting:

When I use `.OnType<Color>().Use(new argbColorPlugin().GetValue());`  the error is different than when I use `.OnType<Color>().Use(new argbColorPlugin());`.

Using `.OnType<Color>().Use(new argbColorPlugin());` gives me this error:
```
at Tynamix.ObjectFiller.Filler`1.GetRandomValue(Type propertyType, FillerSetupItem setupItem)
at Tynamix.ObjectFiller.Filler`1.CreateAndFillObject(Type type, FillerSetupItem currentSetupItem, HashStack`1 typeTracker)
at Tynamix.ObjectFiller.Filler`1.FillInternal(Object objectToFill, HashStack`1 typeTracker)
at Tynamix.ObjectFiller.Filler`1.Create()

System.TypeInitializationException : The type initializer for 'System.Collections.ArrayList' threw an exception.
  ----> System.Exception : The type [ArrayList] was not registered in the randomizer.
```

It's nearly the same error, but refers to ArrayList not being registered instead of Color.

**Comment by Tynamix** [comment]
Ok, the first part of your problem i really can not comprehend. When you want to use a plugin you don't  have to use the `GetValue()` method! Just use it as `.OnType<Color>().Use(new argbColorPlugin());` without the GetValue method. Maybe i missunderstand you. Are you able to make a simple sample project which you can share to clear things up a bit more and where the error is reproduced?

The second part of your problem i can understand. You use an arraylist somewhere in your object hierarchy! ArrayLists are not supported by default by the ObjectFiller.NET. I will change this in the next version! You have two different possibilities to solve that right now.
The easiest way is, to just ignore the type ArrayList like that: `.OnType<ArrayList>().IgnoreIt()`.
The ObjectFiller will ignore the type and will not create instance of it.
If you want, that the ObjectFiller will create an instance of type Arraylist you have to write an own plugin for type ArrayList. Here is a simple implementation for that!

```csharp
        public class ArrayListPlugin<T> : IRandomizerPlugin<ArrayList>
        {
            public ArrayList GetValue()
            {
                ArrayList arrayList = new ArrayList();
                var sourceList = Randomizer<List<T>>.Create();

                foreach (var source in sourceList)
                {
                    arrayList.Add(source);
                }

                return arrayList;
            }
        }
```
After this you can use it like that  `.OnType<ArrayList>().Use(new ArrayListPlugin<string>());`.
It will create an ArrayList with strings... You can also change it to that: `.OnType<ArrayList>().Use(new ArrayListPlugin<int>());`. Then it will create an ArrayList with integers.

The final Console Application looks then like this:
```csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ObjectFillerBugfix
{
    using System.Collections;
    using System.Drawing;

    using Tynamix.ObjectFiller;

    class Program
    {
        public class argbColorPlugin : IRandomizerPlugin<Color>
        {
            private readonly System.Random r = new System.Random();
            private readonly List<Color> allColors =
            new List<Color>()
            {
                System.Drawing.Color.Beige,
                System.Drawing.Color.FromArgb(new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue())
            };

            public Color GetValue()
            {
                return allColors[r.Next(0, allColors.Count)];
            }
        }


        public class ArrayListPlugin<T> : IRandomizerPlugin<ArrayList>
        {
            public ArrayList GetValue()
            {
                ArrayList arrayList = new ArrayList();
                var sourceList = Randomizer<List<T>>.Create();

                foreach (var source in sourceList)
                {
                    arrayList.Add(source);
                }

                return arrayList;
            }
        }


        public class Bug63Poco
        {
            public double SomeNumber { get; set; }
            public Color FontColor { get; set; }
            public Color BackgroundColor { get; set; }
            public ArrayList ArrayList { get; set; }
        }

        static void Main(string[] args)
        {
            Filler<Bug63Poco> filler = new Filler<Bug63Poco>();

            filler.Setup().OnProperty(x => x.SomeNumber).Use(new DoubleRange(10, 1000))
                // !!! SETUP FOR ALL PROPERTIES OF TYPE COLOR AND ARRAYLIST !!!
                .OnType<Color>().Use(new argbColorPlugin())
                .OnType<ArrayList>().Use(new ArrayListPlugin<string>());
                

            Bug63Poco bug63Poco = filler.Create();

            Console.WriteLine(bug63Poco.SomeNumber);
            Console.WriteLine(bug63Poco.FontColor);
            Console.WriteLine(bug63Poco.BackgroundColor);

            foreach (object o in bug63Poco.ArrayList)
            {
                Console.WriteLine(o.ToString());
            }

            Console.ReadLine();
        }
    }
}
```

**Comment by zo0o0ot** [comment]
There aren't any ArrayLists in the object I"m trying to fill.  I am, however, casting objects to different types.  Here's the types that the object uses:

+ float
+ string
+ enum
+ Color
+ bool

Here's how I'm making them:

+ `.OnProperty(x => x.X1).Use((float)new IntRange(10, 100).GetValue())`
+ `.OnProperty(x => x.Face).Use(new MnemonicString(2, 5, 15))`
+ `.OnProperty(x => x.Style).Use((FontStyle)new RandomListItem<int>(0, 1, 2, 4, 8).GetValue())`
+ `.OnProperty(x => x.FontColor).Use(new argbColorPlugin())` or `.OnProperty(x => x.FontColor).Use(System.Drawing.Color.Beige)` or `System.Drawing.Color.FromArgb(new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue())`
+ `.OnProperty(x => x.ShowLines).Use((bool)(new IntRange(0, 1).GetValue() != 0))`

Should I not be doing this typecasting?  It will only let me typecast if I've used GetValue() from the plugin in question, such as IntRange().

**Comment by Tynamix** [comment]
Ok :smile:,
Lets do it step by step....

- `.OnProperty(x => x.X1).Use((float)new IntRange(10, 100).GetValue())`
This is correct. I created an issue that objectfiller will get a floatrange plugin in the next version!
See #66 !

- `.OnProperty(x => x.Face).Use(new MnemonicString(2, 5, 15))`
Very good!

- `.OnProperty(x => x.Style).Use((FontStyle)new RandomListItem<int>(0, 1, 2, 4, 8).GetValue())`
This is not necessary. ObjectFiller will generate random enum values for you. But if you want to use a setupset of valid enum values you can use just `RandomListItem<FontStyle>` instead of `RandomListItem<int>`. I show you in my solution below.

- `.OnProperty(x => x.FontColor).Use(new argbColorPlugin())` or `.OnProperty(x => x.FontColor).Use(System.Drawing.Color.Beige)` or `System.Drawing.Color.FromArgb(new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue())` 
Yes this should all work!

- `.OnProperty(x => x.ShowLines).Use((bool)(new IntRange(0, 1).GetValue() != 0))`
This is senseless... Boolean is no problem for the ObjectFiller!

So here is what i have and it works:

```csharp
    class Program
    {
        public class argbColorPlugin : IRandomizerPlugin<Color>
        {
            private readonly System.Random r = new System.Random();
            private readonly List<Color> allColors =
            new List<Color>()
            {
                System.Drawing.Color.Beige,
                System.Drawing.Color.FromArgb(new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue(), new IntRange(0, 255).GetValue())
            };

            public Color GetValue()
            {
                return allColors[r.Next(0, allColors.Count)];
            }
        }

        public enum FontStyle
        {
            Style1 = 0,
            Style2 = 1,
            Style3 = 2,
            Style4 = 4,
            Style5 = 8,
            Style6 = 16
        }

        public class Bug63Poco
        {
            public float X1 { get; set; }
            public string Face { get; set; }
            public bool ShowLines { get; set; }
            public Color FontColor { get; set; }
            public FontStyle Style { get; set; }
        }

        static void Main(string[] args)
        {
            Filler<Bug63Poco> filler = new Filler<Bug63Poco>();

            filler.Setup()
                .OnType<Color>().Use(new argbColorPlugin())
                .OnProperty(x => x.X1).Use((float)new DoubleRange(1, 100).GetValue())
                .OnProperty(x => x.Face).Use(new MnemonicString(2, 5, 15))
                .OnProperty(x => x.Style).Use(new RandomListItem<FontStyle>(FontStyle.Style2, FontStyle.Style3, FontStyle.Style4));

            Bug63Poco bug63Poco = filler.Create();

            Console.WriteLine(bug63Poco.Face);
            Console.WriteLine(bug63Poco.FontColor);
            Console.WriteLine(bug63Poco.X1);
            Console.WriteLine(bug63Poco.ShowLines);
            Console.WriteLine(bug63Poco.Style);

            Console.ReadLine();
        }
    }
```

**Comment by zo0o0ot** [comment]
I'm feeling a lot better about this, but I am still running into the "ArrayList" error.  I think I'm going to wait until 1.4.2, update the framework from NuGet, and try again.  It seems like at this point, I need to give that a try, since I had issues with 1.4.0 and 1.4.1, and ArrayLists will be added to the randomizer in 1.4.2.

**Comment by Tynamix** [comment]
Seems to be solved
