### ISSUE TITLE
Add option to ignore inherited properties

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#69]
Today I built a search form where I added additional Information for the the UI by inheriting the view model from the actual model:

```
public class Filter
{
    public string Name { get; set; }
}
```

```
public class FilterViewModel : Filter
{
   public string[] AvailableNames {get; set; }
}
```

In this case it would be nice to have an option so the filler generates only data for the ViewModel.

It could be handled the same way as "IgnoreUnknownTypes".
```
var filterFiller = new Filler<FilterViewModel >();
filterFiller.Setup().IgnoreInheritance();
```

**Comment by Tynamix** [comment]
Hmm.. Ok... it would be good to use it on the type API and in the general API... 
```csharp
filler.Setup().OnType<SomeType>().DontFilIInherited()
```

**Comment by Tynamix** [comment]
Change has to be done in the FillInternal method.
This change should just get properties which are declared in the class itself:

```csharp
var properties =
                targetType.GetProperties(BindingFlags.DeclaredOnly).Where(prop => this.GetSetMethodOnDeclaringType(prop) != null).ToArray();
```

**Comment by Tynamix** [comment]
In #81 the documentation will be added to readme.io
