### ISSUE TITLE
Create untyped Randomizer Plugins

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#78]
For complex scenarios it is good to have plugins which decide by their own if they can be used for a specific type or not.

This is not possible with IRandomizerPlugin<out T> because of its concrete typing. That's why it would be nice to have a IRandomizePlugin without typing but with an additional method to check if it can be used.

For example I have following class:

```
public class Address
{
      public string Street { get; set; }
      ...
}
```

Currently it Is not possible to call:

`Randomizer<Address>.Create(new Mnemonic());`

because Mnemonic is of type IRandomizerPlugin<string> and not IRandomizerPlugin<Address>.

The dynamic version of the plugin must then be referenced for each type and property within our resolution routine.

The signature of the plugin could look like:

```
public interface IRandomizerPlugin
{
        bool CanBeUsedOn(Type type);

       object GetData();
}
```

The basic advantage is, that one plugin can be used for multiple types.

**Comment by Tynamix** [comment]
Hmm... whats the benefit again using it like this:

```csharp
        public class Address
        {
            public string Street { get; set; }

            public string Firstname { get; set; }
        }

        [TestMethod]
        public void UseTypeRandomizer()
        {
            var filler = new Filler<Address>();
            filler.Setup().OnType<string>().Use(new MnemonicString(1, 1, 5));

            var address = filler.Create();
            Assert.IsTrue(address.Firstname.Length<6);
            Assert.IsTrue(address.Street.Length < 6);
        }
```

**Comment by HerrLoesch** [comment]
Is ok for me.

**Comment by Tynamix** [comment]
:thumbsup:
