### ISSUE TITLE
Add Setup to ignore all properties, except configured.

### ISSUE THREAD

**Issue by HerrLoesch** [Tynamix/ObjectFiller.NET#83]
Thanks to Entity Framewok, I am currently in a situation where I need to ignore more properties than I actually need for a test. It would be nice to have a method where I can say, that the Filler should ignore every thing which is not configured explicitly.

**Comment by cubikca** [comment]
+1. My list of used properties is much smaller than my list of unused properties for some tests.

**Comment by Tynamix** [comment]
Will look at this ASAP!

**Comment by Tynamix** [comment]
Added as a new feature... Can be used like this:

`Filler<Parent> filler = new Filler<Parent>();
            filler.Setup(true)
               .OnProperty(x => x.SomeId).Use(new IntRange(1, 20));

            var parent = filler.Create();`

**Comment by Tynamix** [comment]
https://objectfillernet.readme.io/reference#explicit-setup
