### ISSUE TITLE
Add support for using an interface when creating an instance of Filler<T>

### ISSUE THREAD

**Issue by abstractlabs** [Tynamix/ObjectFiller.NET#92]
I would like to see the ability to use an interface when creating an instance of a filler for example something like:
`Filler<ISomething> somethingFiller = new Filler<ISomething>(()=>{ return new Something() }).Setup()...`

**Comment by HerrLoesch** [comment]
It is already possible: https://objectfillernet.readme.io/reference#handle-interface-properties

**Comment by abstractlabs** [comment]
If I understand your example you are referring to the property on a filler I was referring to the target object the filler is operating on. When I had read through the filler code I could not see anywhere where this was possible.

Does the example above work in the following way?
var pFiller = new Filler<IAddress>();
pFiller.Setup().OnType<IAddress>().Register<Address>() ?

**Comment by Tynamix** [comment]
The example here https://objectfillernet.readme.io/reference#handle-interface-properties was wrong. It is not `.Regsiter<T>()` ... It is `.CreateInstanceOf<T>`. I fixed it in the documentation. See:
https://objectfillernet.readme.io/reference#handle-interface-properties
