### ISSUE TITLE
Please add unlimited mergeable setup

### ISSUE THREAD

**Issue by HamedFathi** [Tynamix/ObjectFiller.NET#97]
```
    public class User
    {
        public int Id { get; set; }
        public Person Person { get; set; }
        public List<string> Phones { get; set; }

    }

    public class Person
    {
        public Guid Id { get; set; }
        public int No { get; set; }
        public string NationalCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateTime BirthDate { get; set; }
   }
            Filler<Person> pFiller = new Filler<Person>();
            var fillerSetup = pFiller.Setup()
                .OnType<string>().Use("PERSON");

            Filler<User> uFiller = new Filler<User>();
            pFiller.Setup(fillerSetup.Result)
                .OnType<string>().Use("USER");

            User p = uFiller.Create();
```

above example does not work I can not merge Person``s filler with User``s filler. (I dont want to use SetupFor<>)
Can you provide this feature ? of course unlimited Setup() for multiple merge

**Comment by Tynamix** [comment]
Do it like that works:

 Filler<Person> pFiller = new Filler<Person>();
            var fillerSetup = pFiller.Setup()
                .OnType<string>().Use("PERSON");

            Filler<User> uFiller = new Filler<User>();
            uFiller.Setup()
                .OnType<Person>().Use(fillerSetup.Result);

            User p = uFiller.Create();

You can define which FillerSetup shall be used for a specific Type (OnType<Person>().Use(fillerSetup.Result)) or for a specific Property (´OnProperty(x=>x.Person).Use(fillerSetup.Result)`)
